version: '3.4'
services:
  api-server:
    image: vjaos/car-catalog-api-server
    depends_on:
      - db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "8080:8080"

  ui:
    image: vjaos/car-catalog-ui
    depends_on:
      - api-server

  db:
    image: postgres
    volumes:
      - postgres:/data/pgdata
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"

volumes:
  postgres: #Set your database volume here