spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/postgres
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none



  liquibase:
    change-log: classpath:db.changelog/db.changlelog-master.xml
    user: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG